locales: Update Simplified Chinese translations
42bytes-team/wfm-localization pull request #133
Opened 2023-08-12 15:15 UTC by JohnsonRan

2023-08-15 21:33 UTC, lonnstyle requested changes

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> -  "app.user.status.connecting": "连线中...",
连接过于直译
连线相对能够表达出伺服器通讯的意思

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> +  "app.footer.disclaimer.content": "Digital Extremes Ltd.、Warframe 和 Warframe 徽标均为注册商标。全球保留所有权利。本网站与 Digital Extremes Ltd. 或 Warframe 没有任何官方关联。本站所展示的艺术作品、截图、角色或其他可识别特征，均属于 Digital Extremes Ltd. 的知识产权
这句的主从关系也错了
原本的翻译才是对的
Warframe(这个名字)跟Warframe图标都是DE的注册商标
DE本身不是个商标，是家公司

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> +  "app.ws.auctions.errors.banned_from_auction": "您已被此拍卖封禁",
“拍卖”是个死物
没办法封禁别人
可以修改一下句式，比如“您已被禁止参与此拍卖”

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> +  "app.auctions.errors.bids_limit_exceeded": "只有赞助者能拥有超过50项拍卖",
这句应该是说50个出价
🤔最好看看en.json

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> +  "app.settings.verification.code": "验证代码",
代码容易让人联想到源代码
“验证码”就够了，而且这个词挺常见的

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> +  "app.faq.password_storage.description": "您的密码并不是直接储存在我们的数据库里。{br}而是储存一个基于您的密码和盐值生成的HASH值（通过 {link}）。{br}所以没有人（包括我们）可以直接看到您的密码，无需担心。",
用括号没有强调的意味
相对比较像补充信息

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> +  "app.privacy.cookies.storeInfo": "为了方便存储信息（“设置”），我们使用Cookie。同时，我们也可能在网站上使用第三方广告。当这些广告商在网站上投放广告时，可能会使用类似Cookie和Web Beacon的技术，从而向这些广告商（如通过Google AdSense程序的Google）发送一些信息，包括您的IP地址、Internet服务提供商（ISP）、您访
Internet→网络

2023-08-15 21:33 UTC, lonnstyle commented on locales/zh-hans.json
> +  "app.editOrder.top.sell.maxed": "满级",
别移除方括号
那是个UX设计

2023-08-16 02:18 UTC, JohnsonRan commented on locales/zh-hans.json
> -  "app.user.status.connecting": "连线中...",
连线一般是港澳台这么说吧，大陆都说连接。
参考微信海外版为连线中...，国内版则是连线

2023-08-16 02:27 UTC, JohnsonRan commented on locales/zh-hans.json
> +  "app.editOrder.top.sell.maxed": "满级",
en.json 等语言文件也没有这个方括号，不过现在加上了

2023-08-30 04:10 UTC, lonnstyle approved these changes

2023-08-30 04:11 UTC, merged