update russian
42bytes-team/wfm-localization pull request #60
Opened 2021-12-05 01:22 UTC by vanja-san

2021-12-05 16:52 UTC, KycKyc requested changes
Спасибо за PR !

Пробежался по изменениям, выявил пару неточностей, оставил фидбек.  
Как поправим \\ согласуем самое очевидное, проверю на дев-сервере еще разок и повнимательнее =)

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.subtype.radiant": "Сияющий",
На вики названия типов реликвий отличаются от предложенных в PR: 
[Вики](https://warframe.fandom.com/ru/wiki/%D0%A0%D0%B5%D0%BB%D0%B8%D0%BA%D0%B2%D0%B8%D1%8F_%D0%91%D0%B5%D0%B7%D0%B4%D0%BD%D1%8B?so=search)

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.statistics.legend.OpenClose": "Открыт - Закрыт",
"открытие" торгов, "закрытие" торгов (час \\ день)
Соответсвенно цена во время открытия \\ закрытия.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.statistics.volume": "Звук",
Должен быть "Объем" торгов за час\\день

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.editOrder.quantity": "Количество",
Из-за особенности верстки, некоторые слова лучше оставить в виде сокращений.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.placeOrder.itemName.placeholder": "Выберите элемент",
Должен быть предмет, не элемент.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.order.sell": "Продажа",
Тоже что и с 1030

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.order.buy": "Покупка",
По задумке, кнопочка должна иметь призыв к дествию: "купить этот товар, у этого торговца, за эти деньги"
Так как по нажатию на нее, пользователь получает сообщение, которое он должен скопировать в чат, дабы связаться с торговцем.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.order.quantity": "на складе",
Из-за особенности верстки, некоторые слова лучше оставить в виде сокращений.
Иначе они не помещаются  контейнер.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.order.platinum": "{platCount, plural, one {# Platinum} other {# Platinum}} each",
Что-то пошло не так, в конце заменилось на `each`

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.order.bought": "Куплено",
Из-за особенности верстки, некоторые слова лучше оставить в виде сокращений.
Иначе они не помещаются  контейнер.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.reviews.header.user_reviews": "Отзывы пользователя",
Контекст: Заголовок, "отзывы пользователей", дальше идет список отзывов

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.reviews.own.header": "Вы {reviewType}",
Контекст: 
- Ваш репорт
- Ваш отзыв

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.profile.stats.reputation": "/reputation",
Стало на английском вместо русского?

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.profile.auctions.title": "Профиль - {username} | Аукционы",
Аукционы -> контракты  
В англ. варианте таже ошибка, исправим.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.itemPage.masteryLvl": "Мастерство l ур.",
Контекст: "Требуемый уровень мастерства"  
здесь получилось, что-то не понятное.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auctions.modal.riven.option.positive": "Положительное",
Контекст \\ смысл:  
Атрибут "положительный"
Атрибут "отрицательный"

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auctions.modal.riven.label.weapon": "Название оружие",
Название оружи**я**

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auction.riven.reRolls": "Реролл",
Тут остался рерол, выше был "круток".
Терминология должна быть одинаковой везде, и я в целом за "рерол" или "цикл"

Конечно, лучше обратится к устоявщенся терминологии внутри игры, которую используют сами игроки, я честно говоря не в курсе, что сейчас в обиходе.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auction.button.findSimilar": "Найти похожее",
Контекст\\смысл изначального варианта: "Найти похожие аукционы"
В целом разницы не особо много, просто fyi

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auction.button.completed": "Отметить как завершённый",
Боюсь от такой длинной фразы верстку слегка размотает, или слова обрежет.  
Поэтому было выбранно короткое "Завершить"

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auction.tabs.bans": "Запрещены",
Контекст: "Список игроков запрещенных к участию в аукционе."  
Слово "Запрещенны" кажется немного не подходит и звучит странно для этой вкладки.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auction.sister.meta.tags": "сёстры,аукционы,догмат",
В игре используется термин `кува`, так же `кува` используется на линии 388

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auctions.entry.riven.reRolls": "Повторная крутка",
Роллы \\ циклы, сию коммент выше.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.auctions.search.riven.label.reRolls": "Повторные крутки",
Кажется, устоявшийся термин все же Роллы \\ циклы, согласно [вики](https://warframe.fandom.com/ru/wiki/%D0%9C%D0%BE%D0%B4%D1%8B_%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%BC%D0%B0)

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.mods.common": "Обычные",
Описанние редкости мода используется на страничке предметов, так же при создании заказа.
В обоих местах, представлен один конкретный мод, поэтому мне кажется логичным использовать единственное число.

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.order.marker.wtb": "хк",
Я думаю в онлайн играх общепринятым выражением все же является `WTB` \\ `WTS`, ни разу не видел использование терминов `хк` \\ `хп`  
Но, я давно не играл в русскоязычной среде, может что-то поменялось ?

2021-12-05 16:52 UTC, KycKyc commented on locales/ru.json
> +    "app.user.status.ingame": "В сети в игре",
Предложение: Лучше тогда уже сократить до просто "В игре"

2021-12-06 02:56 UTC, vanja-san commented on locales/ru.json
> +    "app.user.status.ingame": "В сети в игре",
Думал тоже сократить до "В игре", но почему-то засомневался.

2021-12-06 02:56 UTC, vanja-san commented on locales/ru.json
> +    "app.order.marker.wtb": "хк",
Честно сказать совсем не шарю за игровые термины, но если и правда такое есть, то соглашусь.

2021-12-06 02:58 UTC, vanja-san commented on locales/ru.json
> +    "app.mods.common": "Обычные",
Согласен.

2021-12-06 02:58 UTC, vanja-san commented on locales/ru.json
> +    "app.auctions.search.riven.label.reRolls": "Повторные крутки",
Извиняюсь за самовольнечество.

2021-12-06 02:59 UTC, vanja-san commented on locales/ru.json
> +    "app.auctions.entry.riven.reRolls": "Повторная крутка",
Согласен

2021-12-06 03:00 UTC, vanja-san commented on locales/ru.json
> +    "app.placeOrder.itemName.placeholder": "Выберите элемент",
Не усмотрел, извиняюсь.

2021-12-06 03:03 UTC, vanja-san commented on locales/ru.json
> +    "app.editOrder.quantity": "Количество",
Мой косяк, я так и думал, но переделать уже не переделал.

2021-12-06 03:03 UTC, vanja-san commented on locales/ru.json
> +    "app.statistics.volume": "Звук",
Понял.

2021-12-06 03:04 UTC, vanja-san commented on locales/ru.json
> +    "app.statistics.legend.OpenClose": "Открыт - Закрыт",
Понял.

2021-12-06 03:04 UTC, vanja-san commented on locales/ru.json
> +    "app.subtype.radiant": "Сияющий",
Не знал что речь о реликвиях, по этому и перевёл как есть.

2021-12-06 03:09 UTC, vanja-san commented
Я видимо тупанул, если всё изначально в норме на сайте, удалите это. 😅

2021-12-06 03:44 UTC, vanja-san commented on locales/ru.json
> +    "app.editOrder.quantity": "Количество",
Почему бы не сделать вот так например:
![изображение](https://user-images.githubusercontent.com/7201687/144783678-0e8fc2f1-c0c2-41aa-be14-d5bd97a69c24.png)

и добавить всплывающий текст на кнопки, типо: "Редактировать", "Удалить", "Сделать невидимым" и т.п.

2021-12-07 00:17 UTC, vanja-san commented
@KycKyc Приношу свои извинения, я впервые занимаюсь таким в PR, по этому не особо знаю, достаточно ли того что я нажал "Resolve converstation"? Нужно ли мне исправлять или вы уже внесли исправления?

2022-01-10 16:08 UTC, KycKyc commented
@vanja-san Нужно исправить в своем репозитории и запушить изменения, гитхаб автоматом обновит PR.
Все топики я потом позыкрываю =)
А, вы видмо закрыли PR ^^

2022-01-30 18:45 UTC, KycKyc commented
Обновил PR, ребейзнув вашу ветку.  
Если хотите продолжить работу над этим PR, то понадобится:
```
git fetch
git switch patch-1
git reset --hard origin/patch-1
```

Так же я докинул пару правок.  
К сожалению, у меня не так много времени чтобы проверить и вычитать все =(  
На данный момент могу сказать, что надо будет еще отредактировать TOS и Privacy.  
С моей стороны надо будет проверить. что все изменения влезут в интерфейс.

2022-01-31 17:19 UTC, vanja-san commented
@KycKyc Никогда не работал с git, можно по подробнее. 😓

2022-01-31 18:40 UTC, KycKyc commented
@vanja-san Ничего страшного =)  
Можете связаться со мной через дискорд: `KycKyc#6138`  
Или зайти на наш сервер и там найти меня, так же роль переводчика выдадим: https://discord.gg/wfm

Смогу объяснить побыстрее, чем через комменты в гитхабе.

2022-05-06 11:25 UTC, DORANDKOR requested changes
Так, ну предварительно накидал, пока не надоело, вот вообщем-то

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.errors.incorrect_request": "Неправильный запрос.",
`неверный` будет уместнее здесь, как мне кажется

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.errors.permission_denied": "Разрешение отклонено",
звучит странно, прошлое сойдет

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.chat.user_not_exist": "Пользователя не существует",
нету точки (если уж везде кроме этого места она есть, то значит ошибка)

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.post_order.limit_exceeded": "Только покровители могут иметь более 100 заказов одновременно.",
`Покровители` - слишком непонятно, `Участники Патреона`, `Патроны` будет уместнее.

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.alert.account.openSettings": "Открыть настройки"
пропала запятая за кавычками

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.buttons.paginator.last": "Последний",
это страницы, насколько я понимаю, поэтому женский род

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.buttons.paginator.first": "Первый",
это страницы, насколько я понимаю, поэтому женский род

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.polarity.any": "Любой",
Полярность - ж.р.

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.items.groups.sentinel": "Страж",
группа со стражами, мн. ч.

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.user.status.ingame": "В игре",
Лучше использовать старые названия, привычные игрокам

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.user.status.online": "В сети",
Лучше использовать старые названия, привычные игрокам

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.user.status.offline": "Не в сети",
Лучше использовать старые названия, привычные игрокам

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.order.marker.bought": "Купленно",
с одной н

2022-05-06 11:25 UTC, DORANDKOR commented on locales/ru.json
> +  "app.menu.auctions.subscript": "Моды разлома | Личи | Сёстра",
`Моды разлома | Личи | СёстрЫ`, лучше использовать `Аукционы`, потому что `Контракты` - не совсем понятное название

2022-05-06 13:36 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.menu.auctions.subscript": "Моды разлома | Личи | Сёстра",
Я так понимаю, что это из раздела с аукционами по мрам, личам, сёстрам? Где люди могут делать ставки на эти товары. Так что мне кажется стоит оставить "аукционы"

2022-05-06 13:41 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.polarity.any": "Любой",
Возможно нужно оставить "любая", не хватает контекста

2022-05-06 18:51 UTC, IStormtrooperI reviewed
я очень много пропустил, очень много из этого зависит от контекста и я в целом не хочу той частью заниматься

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.general.description": "Ведущая торговая площадка Warframe, где вы можете покупать и продавать предметы из хранилища и не из хранилища, а также наборы Waframe, части, оружие, моды, реликвии, че
Предлагаю такой вариант (по сути то же что и предложил DORANDKOR):
`На Варфрейм маркете вы можете купить и продать: Моды, Чертежи, Праймы, Реликвии, Моды разлома. Так же доступны аукционы Модов Разлома, Личей Кувы и Сестёр Парвоса.`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.form.not_a_bool": "Может быть True или False (Bool)",
оставить как было

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.form.too_many_requests": "Вы превысили лемит попыток на вход или регистрацию. Повторите попытку через 1 минуту.",
согласен

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.theme.water": "Чистая вода",
спорная строка, не хватает контекста

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.review.error_same_user": "Нельзя написать отзыв о себе.",
оставить как было

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.review.not_exist": "Отзыва не существует.",
я бы исправил на это
`Отзыв не существует.`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.review.limit_exceeded": "Вы превысили лимит ежедневных просмотров (15 просмотров в день).",
согласен

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.errors.unauthorized": "Несанкционированный доступ, войдите в систему.",
согласен

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.account.email_not_exist": "Электронная почта не зарегистрирована.",
По смыслу здесь написано, что такой почты не существует в целом, но по идее ошибка означает что-то вроде этого, возможно стоит еще переформулировать:
`Электронная почта не была использована для регистрации аккаунта на этой платформе.`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.errors.permission_denied": "Разрешение отклонено",
согласен, но нужно добавить точку, если уж она везде

`Доступ запрещен.`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.errors.incorrect_request": "Неправильный запрос.",
согласен и это то как было раньше

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.errors.not_verified": "Ваша учётная запись не подтверждена, подтвердите её.",
возможно стоит убрать совет, так как его не в остальных ошибках и оставить только:
`Ваша учётная запись не подтверждена.`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.errors.banned": "Ваша учётная запись была приостановлена (поищите причину на странице своего профиля)",
я бы исправил на это
`Ваша учётная запись была приостановлена (причина указана в вашем профиле)`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.errors.last_service": "Невозможно удалить последнюю службу. (по техническим причинам)",
`служба` и `связь`, непонятно что правильнее, необходим контекст

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.post_order.item_not_tradable": "Товар не подлежит обмену (перезагрузите сайт)",
я бы исправил на это
учитывая, что везде используется слово `Предмет`, а здесь `Товар`
`Предмет не подлежит обмену (перезагрузите страницу)`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.alert.account.openSettings": "Открыть настройки"
согласен, файл полетит

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.platforms.xbox": "Xbox",
я бы исправил на это
`XBOX`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.platforms.pc": "Pc",
я бы исправил на это
`PC`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.platforms.ps4": "Ps4",
я бы исправил на это
`PS4`

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.items.groups.sentinel": "Страж",
оставить как было

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.user.status.ingame": "В игре",
согласен

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.user.status.online": "В сети",
согласен

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.user.status.offline": "Не в сети",
согласен

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.user.status.lastSeen": "Последний вход: ",
оставить как было

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.menu.browse_patforms": "Обзор",
не хватает контекста, не понятно что лучше

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.menu.auctions.subscript": "Моды разлома | Личи | Сёстра",
я нашел где это расположено и теперь даже не знаю как эту длинную строку туда засунуть, возможно стоит где-нибудь в середине строки поставить многоточие, либо взять вариант предложенный DORANDKOR для сокращения этой строки

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.footer.terms": "Условия предоставления услуг",
спорно

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.footer.contribute": "Вклад (GitHub)",
оставить как было

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.footer.online.traders": "Торговцев в сети",
если оставляем статусы старые, то и эти строки (136,137) надо оставить как было

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.filters.platinum": "Платина",
спорно, контекст

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.mods.peculiar": "Особый",
зависит от контекста:

в игре есть:

Обычные(бронзовые), 
Необычные(серебряные), 
Редкие(желтые), 
Легендарные(белые), 
Моды разлома
 все эти выше я убираю, так как они есть рядом с этой строкой.

остаются:
 

Сломанные одного из видов - (бронзовые, серебряные, желтые), 
Специфичные(они как раз `peculiar` судя по вики и сайту - https://warframe.fandom.com/wiki/Peculiar_Bloom)
Реквиемы (целые и сломанные)
Гальванизированные
Амальгама

2022-05-06 18:51 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.subtype.exceptional": "Исключительный",
1082-1086 оставить как было

2022-05-22 14:10 UTC, IStormtrooperI commented on locales/ru.json
> -  "app.profile.auctions.title": "Profile - {username} | Auctions",
`Профиль - {username} | Аукционы`

2022-06-15 18:23 UTC, IStormtrooperI requested changes

2022-06-15 18:23 UTC, IStormtrooperI commented on locales/ru.json
> +  "app.elements.cold": "Лёд",
Оставить `Холод`, остальные элементы надо изменить

2022-08-18 15:14 UTC, lonnstyle commented
outdated, most are translated in other PR

2022-08-18 15:14 UTC, closed without merging